# Generated by Django 2.2.7 on 2019-11-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0002_auto_20191128_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(verbose_name=1),
        ),
    ]
