# Generated by Django 2.2.7 on 2019-12-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0007_orders_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
