# Generated by Django 3.0 on 2019-12-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0009_auto_20191215_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.CharField(default='', max_length=50),
        ),
    ]
