# Generated by Django 3.0 on 2019-12-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0010_auto_20191215_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='priceold',
            new_name='sprice',
        ),
    ]
