# Generated by Django 3.0 on 2019-12-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0013_remove_product_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
    ]
