# Generated by Django 3.0 on 2019-12-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0014_remove_product_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='', upload_to='EShop/images'),
        ),
    ]
