# Generated by Django 3.0 on 2019-12-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0016_auto_20191215_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
    ]
