# Generated by Django 3.0 on 2019-12-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0017_remove_product_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='', null=True, upload_to='EShop/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='', null=True, upload_to='EShop/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='', null=True, upload_to='EShop/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(default='', null=True, upload_to='EShop/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sprice',
            field=models.IntegerField(null=True, verbose_name=0),
        ),
    ]
