# Generated by Django 3.0 on 2019-12-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0019_auto_20191215_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sprice',
        ),
    ]
