# Generated by Django 3.0 on 2019-12-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0021_auto_20191215_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
    ]
