# Generated by Django 3.0 on 2019-12-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0022_auto_20191215_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sprice',
            field=models.IntegerField(),
        ),
    ]
