# Generated by Django 3.0 on 2019-12-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0023_auto_20191215_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productcategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='', max_length=50)),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
