# Generated by Django 3.0 on 2019-12-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0024_auto_20191225_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
    ]
