# Generated by Django 3.0 on 2020-01-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0025_auto_20191225_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
