# Generated by Django 3.0 on 2020-01-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0026_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Unit',
            field=models.CharField(default='', max_length=50),
        ),
    ]
