# Generated by Django 3.0 on 2020-01-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0027_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Qty',
            field=models.IntegerField(default=0),
        ),
    ]
