# Generated by Django 3.0 on 2020-01-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop', '0028_product_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('newsletter_id', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
    ]
