# Generated by Django 3.0 on 2019-12-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_user_id',
            name='role',
            field=models.CharField(default='', max_length=20),
        ),
    ]
